server:
  port: 9090
spring:
  datasource:
    driver-class-name: 'org.postgresql.Driver'
    username: root
    password: root
    url: jdbc:postgresql://db:5432/tms
  jpa:
    database: POSTGRESQL
    show-sql: false