version: "3.9" #version of docker-compose
services:
  db:
    image: "postgres:13.4-alpine"
    container_name: "demo-postgres"
    environment:
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=root
      - POSTGRES_DB=tms
    ports:
      - "35432:5432"
#  flyway-migrator:
#    image: boxfuse/flyway:5-alpine
#    command: -url=jdbc:postgresql://db:5432/tms -schemas=public -baselineOnMigrate=true -user=root -password=root migrate
#    volumes:
#      - ./src/main/resources/db/migration:/flyway/sql
#    depends_on:
#      - db
