version: "3.9" #version of docker-compose
services:
  db:
    image: "postgres:13.4-alpine"
    container_name: "demo-postgres"
    environment:
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=root
      - POSTGRES_DB=tms
    ports:
      - "35432:5432"
  message-service:
    container_name: "message-service"
    image: message-service:latest
    ports:
      - "9090:9090"
    depends_on:
    - db
