spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    user: root
    password: root
    url: jdbc:postgresql://localhost:35432/tms
  jpa:
    database: POSTGRESQL
    show-sql: false
    hibernate:
      ddl-auto: validate
  thymeleaf:
    prefix: classpath:/templates/
    suffix: .html
  hasher:
    salt: SECRET